apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-dev
  namespace: argocd
spec:
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/luisbianconi/aulao-pipeline.git
      revision: HEAD
      branches:
      - "dev-*"
  template:
    metadata:
      name: '{{branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: '{{branch}}'
        path: 'dev/helloworld-docker/helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{branch}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
