apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-dev
  namespace: argocd-prd
spec:
  generators:
  - git:
      repoURL: https://github.com/luisbianconi/aulao-pipeline.git
      revision: HEAD
      files:
      - path: "dev/helloworld-docker/helm/Chart.yaml"
      branches:
      - "dev-*"
      branchLimit: 1
  template:
    metadata:
      name: 'development'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: '{{branch}}'
        path: 'dev/helloworld-docker/helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'development'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
