apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-dev
  namespace: argocd
spec:
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: luisbianconi
        repo: aulao-pipeline
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'dev-{{branch_slug}}-{{number}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: '{{head_sha}}'
        path: 'dev/helloworld-docker/helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev-{{branch_slug}}-{{number}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
