apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd-prd
spec:
  project: 'default'
  source:
    repoURL: 'https://github.com/luisbianconi/descomplicando-gitops-no-kubernetes-argocd.git'
    targetRevision: feat/day3
    path: giropops-senhas/helm
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
