apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-kube-prometheus
  namespace: argocd-prd
spec:
  generators:
  - list:
      elements:
      - env: production
  template:
    metadata:
      name: 'production'
    spec:
      project: default
      source:
        repoURL: https://github.com/prometheus-community/helm-charts.git
        targetRevision: 'main'
        path: 'helm-charts/charts/kube-prometheus-stack'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'monitoring'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
