apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-prod
  namespace: argocd-prd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/luisbianconi/aulao-pipeline.git
      revision: HEAD
      branchFilter: "prd-*"
  template:
    metadata:
      name: '{{.branch}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: '{{.branch}}'
        path: 'prd/helloworld-docker/helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.branch}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
