apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-prod
  namespace: argocd-prd
spec:
  generators:
  - list:
      elements:
      - env: production
  template:
    metadata:
      name: 'production'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: 'main'
        path: 'prd/helloworld-docker/helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'production'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
