apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prd-apps-da-pipe
  namespace: argocd-prd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/luisbianconi/aulao-pipeline.git
      revision: HEAD
      directories:
      - path: prd/*/helm
  template:
    metadata:
      name: prd-{{index .path.segments 1}}
    spec:
      project: "default"
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true