apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-prod-approved
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/luisbianconi/aulao-pipeline.git
      revision: HEAD
      directories:
      - path: prd/*/helm
  template:
    metadata:
      name: 'prod-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisbianconi/aulao-pipeline.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
